#!/bin/sh
# A script to run Textmaker.

MACHINE=$(uname -m)

[[ $MACHINE == "x86_64" ]] && LIBDIR_SUFFIX="64" || LIBDIR_SUFFIX=""

# fix for spamming crap directly into the root of the home directory
REAL_HOME="$HOME"
export HOME="$HOME/.softmaker"
ln -s "../.config" "$REAL_HOME/.softmaker/.config" 2>/dev/null
ln -s "../.local" "$REAL_HOME/.softmaker/.local" 2>/dev/null

exec /usr/lib$LIBDIR_SUFFIX/freeoffice/textmaker "$@"
