#!/bin/sh
#========================================================================================
# Script to check if the NVIDIA GPU is currently being used.
# Hibernation doesn't work when NVIDIA is active, so ensure this script returns 0
# before hibernating, or deal with the consequences.
#========================================================================================

# check if any process has the __NV_PRIME_RENDER_OFFLOAD variable set
RES_OFFLOAD="$(cat -v /proc/**/environ 2>/dev/null | grep __NV_PRIME_RENDER_OFFLOAD)"
RES_OFFLOAD=$?

# check if any process is currently using the NVIDIA UVM kernel module (CUDA)
RES_CUDA="$(lsof /dev/nvidia-uvm 2>/dev/null)"
RES_CUDA=$?

if [[ "$RES_OFFLOAD" == 0 || "$RES_CUDA" == 0 ]]; then
    # NVIDIA GPU is currently in use
    echo 1
else
    # NVIDIA GPU is currently not used
    echo 0
fi

# ensure the exit status is always zero
exit 0
