diff --git a/Makefile b/Makefile
index 009e18f..323ba65 100644
--- a/Makefile
+++ b/Makefile
@@ -20,11 +20,11 @@ DNSMASQDEPS = config.h dhcp-protocol.h dns-protocol.h radv-protocol.h dhcp6-prot
 DNSMASQOBJ = arp.o dbus.o domain.o lease.o outpacket.o rrfilter.o auth.o dhcp6.o edns0.o log.o poll.o slaac.o blockdata.o dhcp.o forward.o loop.o radv.o tables.o bpf.o dhcp-common.o helper.o netlink.o rfc1035.o tftp.o cache.o dnsmasq.o inotify.o network.o rfc2131.o util.o conntrack.o dnssec.o ipset.o option.o rfc3315.o crypto.o dump.o ubus.o metrics.o
 
 # Get git commit version and date
-GIT_BRANCH := $(shell git branch | sed -n 's/^\* //p')
+GIT_BRANCH := master
 GIT_HASH := $(shell git --no-pager describe --always --dirty)
-GIT_VERSION := $(shell git --no-pager describe --tags --always --dirty)
-GIT_DATE := $(shell git --no-pager show --date=short --format="%ai" --name-only | head -n 1)
-GIT_TAG := $(shell git describe --tags --abbrev=0)
+GIT_VERSION := v4.3.1
+GIT_DATE := 2019-05-26
+GIT_TAG := v4.3.1
 
 # Is compiler at least gcc version 8? We cannot do ifgt in Makefile, so we use the shell expr command
 GCCVERSION8 := $(shell expr `$(CC) -dumpversion | cut -f1 -d.` \>= 8)
@@ -97,8 +97,7 @@ CCFLAGS=-std=gnu11 -I$(IDIR) $(WARNFLAGS) -D_FILE_OFFSET_BITS=64 $(HARDENING_FLA
 # for FTL we need the pthread library
 # for dnsmasq we need the nettle crypto library and the gmp maths library
 # We link the two libraries statically. Although this increases the binary file size by about 1 MB, it saves about 5 MB of shared libraries and makes deployment easier
-#LIBS=-pthread -lnettle -lgmp -lhogweed
-LIBS=-pthread -lrt -Wl,-Bstatic -L/usr/local/lib -lhogweed -lgmp -lnettle -Wl,-Bdynamic
+LIBS=-pthread -lnettle -lrt -lgmp -lhogweed
 # Flags for compiling with libidn : -lidn
 # Flags for compiling with libidn2: -lidn2
 
