#!/bin/bash

ld="$(basename "$0")"
args=()

for x in "$@"; do
    if [[ "$x" == *"-lstdc++"* ]]; then
        args+=("-lc++")
    elif [[ "$x" == *"-lgcc_s"* ]]; then
        args+=("-lunwind")
    else
        args+=("$x")
    fi
done

exec "clang++" "${args[@]}"
