#!/bin/sh

cc="clang++"
libc="/usr/musl"
libc_inc="/usr/musl/include"
libc_lib="/usr/musl/lib64"
thisdir="`cd "$(dirname "$0")"; pwd`"

# determine correct library path for multilib build
case " $@ " in *\ -m32\ *) libc_lib="/usr/musl/lib" ;; *) libc_lib="/usr/musl/lib64" ;; esac

# prevent clang from running the linker (and erroring) on no input.
sflags=
eflags=
for x ; do
    case "$x" in
        -l*) input=1 ;;
        *) input= ;;
    esac
    if test "$input" ; then
        sflags="-l-user-start"
        eflags="-l-user-end"
        break
    fi
done

# invoke compiler
# FIXME: nasty -isystem and #include_next workaround
exec $cc \
    -B"$thisdir" \
    -fuse-ld=musl-clang++ \
    -nostdinc \
    --sysroot "$libc" \
    -isystem "$libc_inc/c++/v1" \
    -isystem "$libc_inc" \
    -isystem "$libc_inc/c++/v1" \
    -isystem "$libc_inc" \
    -L-user-start \
    $sflags \
    "$@" \
    $eflags \
    -L"$libc_lib" \
    -L-user-end
